print("Jan Eris Saludo")
print("Pangi, Gasan, Marinduque")
print("January 19, 2002")
print("Marinduque State Collelge")
print("Bachelor of Science in Information Technology")
print("2F")
print("Playing Piano")
print("Developing Games")
print("Playing Valorant")
print("Creating Pixel Art")
print("Modeling in Blender")